name: Updates Check
on:
  schedule:
    # every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  check-for-updates:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check for updates
        run: |
          ./update.sh 220070 cmw
          ./update.sh 740 csgo
          ./update.sh 232250 tf2
      - name: Commit any changes
        uses: actions-x/commit@v6