name: Updates Check
on:
  push:
    branches:
      - main
  #TMP#schedule:
  #TMP#  # every 15 minutes
  #TMP#  - cron: '*/15 * * * *'

jobs:
  check-for-updates:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check for updates
        run: |
          ./update.sh 220070 cmw
          ./update.sh 740 csgo
          ./update.sh 232250 tf2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit any changes
        uses: actions-x/commit@v6